Fix space in code, add svg partials
Kseniia-FS/valtech-internship pull request #6
Opened 2022-03-28 08:09 UTC by Kseniia-FS

2022-03-28 09:44 UTC, zaldrox requested changes

2022-03-28 09:44 UTC, zaldrox commented on backend/src/js/addToCartFromThumbs.js
>      const page = Number(window.location.search.slice(6)[0]);
Wrong approach that will lead to lots of bugs in the future. Change the way retrieving the page

2022-03-28 09:44 UTC, maksymsaltykov commented on backend/src/js/compare.js
> +
Remove this empty line

2022-03-28 09:44 UTC, maksymsaltykov commented on backend/src/js/favorite.js
> +
remove 2 empty lines

2022-03-28 09:44 UTC, zaldrox commented on backend/src/js/favorite.js
> +
remove this empty line

2022-03-28 09:44 UTC, zaldrox commented on backend/src/js/favorite.js
remove this empty line

2022-03-28 09:44 UTC, zaldrox commented on backend/src/js/filter.js
> +
remove this empty line and have a better recheck of this point through all your project

2022-03-28 09:44 UTC, maksymsaltykov commented on backend/src/js/shoppingCart.js
> +    cartTable.innerHTML = `<h2 style="text-align: center; margin-bottom: 200px;
move it to the template

2022-03-28 09:44 UTC, zaldrox commented on backend/src/js/shoppingCart.js
> +    cartTable.innerHTML = `<h2 style="text-align: center; margin-bottom: 200px;
avoid inline styles

2022-03-28 13:02 UTC, Kseniia-FS commented on backend/src/js/shoppingCart.js
> +    cartTable.innerHTML = `<h2 style="text-align: center; margin-bottom: 200px;
changes added

2022-03-29 20:37 UTC, zaldrox approved these changes

2022-03-30 08:39 UTC, merged